## Device settings, provide one of the following:
##  - device_id (most secure if you use multiple devices)
##  - port + baudrate information
##  - nothing: the driver scans for devices and selects the first found.
# device_id: '077007EF' # uppercase hex string
port: '/dev/ttyS0'
baudrate: 115200 # non necessary for some devices

## Log file (optional), placed in ~/.ros/ otherwise use absolute path
# log_file: log.mtb

publisher_queue_size: 5
gps_fix_topic: "/alpha_rise/gps/fix"
set_lla_with_gps_fix: false
# TF transform frame_id (default: imu_link), you may want to change it if you use multiple devices

# Message publishers
pub_imu: true
pub_quaternion: false
pub_mag: true
pub_angular_velocity: false
pub_acceleration: false
pub_free_acceleration: false
pub_dq: false
pub_dv: false
pub_sampletime: false
pub_temperature: false
pub_pressure: false
pub_gnss: false
pub_twist: false
pub_transform: false
pub_positionLLA: false
pub_velocity: false
pub_euler: true

quaternion_freq: 100
magnetic_field_freq: 100
acceleration_freq: 100
rate_of_turn_freq: 100
euler_angles_freq: 100


## Sensor standard deviation [x,y,z] (optional)
## This value is used to override the covariance matrix in sensor_msgs/Imu and
## sensor_msgs/MagneticField messages.
linear_acceleration_stddev: [0.01, 0.01, 0.01] # [m/s^2]
angular_velocity_stddev: [0.01, 0.01, 0.01] # [rad/s]

orientation_stddev: [0.01, 0.01, 0.01] # [rad]
magnetic_field_stddev: [0.01, 0.01, 0.01] # [Tesla]
# 
onboard_filter_profile: Robust/NorthReference